name: community-release-env
on:
  release:
    types: [published]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout source'
        uses: actions/checkout@v4

      - name: Get release info
        id: get_release_name
        run: |
          RELEASE_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          LATEST_RELEASE=$(echo "$RELEASE_JSON" | jq -r '.tag_name')

          echo "RELEASE_TAG=$LATEST_RELEASE" >> $GITHUB_ENV

      - name: Construct and export env vars from copier answers
        shell: bash
        run: |
          PACKAGE_NAME=$(grep -oP '^package_name:\s*\K.+' .copier-answers.yml || true)
          TARGET_DISTRO=$(grep -oP '^target_distro:\s*\K.+' .copier-answers.yml || true)

          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "TARGET_DISTRO=$TARGET_DISTRO" >> $GITHUB_ENV

      - name: Modify existing release env file with new release tag
        run: |
          pip install --upgrade pyyaml
          python - <<EOF
          import os
          import yaml

          release_env_path = \
            "environment-files/$PACKAGE_NAME-qiime2-$TARGET_DISTRO-release.yml"

          if not os.path.exists(release_env_path):
            raise Exception(f"{release_env_path} not found.")

          with open(release_env_path, "r") as fh:
            content = fh.read()
            data = yaml.safe_load(content)

            raise ValueError(data["dependencies"]["pip"])
