name: Test newly minted release environment file
on:
  push:
    branches:
      - 'automated/release-*-env-file-updates'

jobs:
  test-install:
    runs-on: ${{ matrix.os }}
    strategy:
    matrix:
      os: [ubuntu-latest, macos-13]

    steps:
    - uses: actions/checkout@v4

    - name: Set up conda
      uses: qiime2-cutlery/setup-miniconda@v3
      with:
        activate-environment: test-env
        miniforge-version: latest

    - name: Detect newly added release env file
      id: detect-env-file
      run: |
        ENV_FILE=$(git diff --name-only HEAD^ HEAD | grep '^environment-files/.*-release-.*\.yml' || true)
        if [[ -z "$ENV_FILE" ]]; then
          echo "No new release environment file found."
          exit 1
        fi
        echo "ENV_FILE=$ENV_FILE" >> $GITHUB_OUTPUT

    - name: Try installing new release env file
      run: |
        conda env create -n test-release-env -f ${{ steps.detect-env-file.outputs.ENV_FILE }}

    - name: Activate and check version info
      run: |
        source "$(conda info --base)/etc/profile.d/conda.sh"
        conda activate test-release-env
        conda list
